"""add_refresh_token

Revision ID: 47a9357c521c
Revises: 919795d7f683
Create Date: 2026-08-27 13:38:00.008799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a9357c521c'
down_revision: Union[str, None] = '919795d7f683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_integrations', sa.Column('refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_integrations', 'refresh_token')
    # ### end Alembic commands ###
