"""add auth schemas

Revision ID: 909a7128cbf5
Revises: ff4df9eb56e7
Create Date: 2026-08-18 08:01:58.559582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909a7128cbf5'
down_revision: Union[str, None] = 'ff4df9eb56e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
