"""Add n11_url to products

Revision ID: b2d13ee9097f
Revises: 47a9357c521c
Create Date: 2026-09-14 14:20:52.946885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d13ee9097f'
down_revision: Union[str, None] = '47a9357c521c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('pazarama_category_id', sa.String(), nullable=True))
    op.add_column('products', sa.Column('pazarama_brand_id', sa.String(), nullable=True))
    op.add_column('products', sa.Column('images_json', sa.String(), nullable=True))
    op.add_column('products', sa.Column('n11_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'n11_url')
    op.drop_column('products', 'images_json')
    op.drop_column('products', 'pazarama_brand_id')
    op.drop_column('products', 'pazarama_category_id')
    # ### end Alembic commands ###
