"""add integrations table

Revision ID: e519b5ae3417
Revises: 909a7128cbf5
Create Date: 2026-08-18 08:12:19.616570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e519b5ae3417'
down_revision: Union[str, None] = '909a7128cbf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('api_secret', sa.String(), nullable=True),
    sa.Column('store_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_integrations_id'), 'marketplace_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_integrations_marketplace_name'), 'marketplace_integrations', ['marketplace_name'], unique=False)
    op.create_index(op.f('ix_marketplace_integrations_tenant_id'), 'marketplace_integrations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_integrations_tenant_id'), table_name='marketplace_integrations')
    op.drop_index(op.f('ix_marketplace_integrations_marketplace_name'), table_name='marketplace_integrations')
    op.drop_index(op.f('ix_marketplace_integrations_id'), table_name='marketplace_integrations')
    op.drop_table('marketplace_integrations')
    # ### end Alembic commands ###
